scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 10s
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "user-score"
    scrape_interval: 10s
    static_configs:
      - targets: ["localhost:8080"]
